<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class ImageMetadata
{
    /**
     * @var string
     */
    protected $lastTagTime;

    /**
     * @return string|null
     */
    public function getLastTagTime(): ?string
    {
        return $this->lastTagTime;
    }

    /**
     * @param string|null $lastTagTime
     *
     * @return self
     */
    public function setLastTagTime(?string $lastTagTime): self
    {
        $this->lastTagTime = $lastTagTime;

        return $this;
    }
}
