<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class ImageID
{
    /**
     * @var string
     */
    protected $iD;

    /**
     * @return string|null
     */
    public function getID(): ?string
    {
        return $this->iD;
    }

    /**
     * @param string|null $iD
     *
     * @return self
     */
    public function setID(?string $iD): self
    {
        $this->iD = $iD;

        return $this;
    }
}
