<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class PluginInterfaceType
{
    /**
     * @var string
     */
    protected $prefix;
    /**
     * @var string
     */
    protected $capability;
    /**
     * @var string
     */
    protected $version;

    /**
     * @return string|null
     */
    public function getPrefix(): ?string
    {
        return $this->prefix;
    }

    /**
     * @param string|null $prefix
     *
     * @return self
     */
    public function setPrefix(?string $prefix): self
    {
        $this->prefix = $prefix;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getCapability(): ?string
    {
        return $this->capability;
    }

    /**
     * @param string|null $capability
     *
     * @return self
     */
    public function setCapability(?string $capability): self
    {
        $this->capability = $capability;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getVersion(): ?string
    {
        return $this->version;
    }

    /**
     * @param string|null $version
     *
     * @return self
     */
    public function setVersion(?string $version): self
    {
        $this->version = $version;

        return $this;
    }
}
