<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class ProgressDetail
{
    /**
     * @var int
     */
    protected $current;
    /**
     * @var int
     */
    protected $total;

    /**
     * @return int|null
     */
    public function getCurrent(): ?int
    {
        return $this->current;
    }

    /**
     * @param int|null $current
     *
     * @return self
     */
    public function setCurrent(?int $current): self
    {
        $this->current = $current;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getTotal(): ?int
    {
        return $this->total;
    }

    /**
     * @param int|null $total
     *
     * @return self
     */
    public function setTotal(?int $total): self
    {
        $this->total = $total;

        return $this;
    }
}
