<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class TaskStatus
{
    /**
     * @var string
     */
    protected $timestamp;
    /**
     * @var string
     */
    protected $state;
    /**
     * @var string
     */
    protected $message;
    /**
     * @var string
     */
    protected $err;
    /**
     * @var TaskStatusContainerStatus
     */
    protected $containerStatus;

    /**
     * @return string|null
     */
    public function getTimestamp(): ?string
    {
        return $this->timestamp;
    }

    /**
     * @param string|null $timestamp
     *
     * @return self
     */
    public function setTimestamp(?string $timestamp): self
    {
        $this->timestamp = $timestamp;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getState(): ?string
    {
        return $this->state;
    }

    /**
     * @param string|null $state
     *
     * @return self
     */
    public function setState(?string $state): self
    {
        $this->state = $state;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getMessage(): ?string
    {
        return $this->message;
    }

    /**
     * @param string|null $message
     *
     * @return self
     */
    public function setMessage(?string $message): self
    {
        $this->message = $message;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getErr(): ?string
    {
        return $this->err;
    }

    /**
     * @param string|null $err
     *
     * @return self
     */
    public function setErr(?string $err): self
    {
        $this->err = $err;

        return $this;
    }

    /**
     * @return TaskStatusContainerStatus|null
     */
    public function getContainerStatus(): ?TaskStatusContainerStatus
    {
        return $this->containerStatus;
    }

    /**
     * @param TaskStatusContainerStatus|null $containerStatus
     *
     * @return self
     */
    public function setContainerStatus(?TaskStatusContainerStatus $containerStatus): self
    {
        $this->containerStatus = $containerStatus;

        return $this;
    }
}
